events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=5s;

    # Define upstream servers (Flask instances)
    upstream flask_app {
        # Docker Compose resolves 'web' to all Flask containers
        server web:5002;
    }

    # HTTP server
    server {
        listen 80;
        server_name _;

        # Route all requests to Flask
        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}